ChromaticData = ChromaticData or {}

-- Items
ChromaticData.ITEM_ELEMENT_SKIP = {
    [5863] = true, --guild charter
}

-- Phrases
ChromaticData.EXCEPTIONS = {
    -- Arcane
"Arcane Intellect", 
"Arcane Brilliance", 
"Arcane Explosion", 
"Arcane Missiles",
"Arcane Instability", 
"Arcane Talents", 
"Arcane Resilience", 
"Arcane Shot",
"Arcane Detonation", 
"Arcane Protection", 
"Arcane Crystal", 
"Arcane crystals",
"Arcane Elixir", 
"Arcane Powder", 
"Arcane Bomb", 
"Arcane energy", 
"Arcane Might",
"Arcane Dust", 
"Arcane Armor", 
"Arcane Evasion", 
"Arcane Shielding", 
"Arcane Blast",
"of the Arcane", 
"Arcane Tarot", 
"Arcane Barrage", 
"Arcane Power", 
"Arcane Khorium",
"arcane magic",
"_Arcane_", --Skada compatibility
    -- Fire
"Fire Talents", 
"Fire Ward", 
"Fire Shield", 
"Fire shield", 
"Fire Blast", 
"Inner Fire",
"Faerie Fire", 
"Fire Totem", 
"fire totem", 
"Fire Nova", 
"Fire Resistance Totem",
"fire every", 
"Fire trap", 
"fire trap", 
"Rapid Fire", 
"Fire Oil", 
"Elemental Fire",
"Essence of Fire", 
"Heart of Fire", 
"of Fire", 
"Fire Protection", 
"Fire Goggles",
"Keep away from fire.", 
"liquid fire", 
"ring of fire", 
"Earth, Fire", 
"Primal Fire",
"primal fire", 
"fire at enemies", 
"Fire Festival", 
"Eternal Fire", 
"eternal fire",
"fel fire", 
"Crystallized Fire", 
"crystallized fire", 
"Fire Leaf", 
"Air, Fire",
"into Fire", 
"Fire into", 
"fire and gems", 
"element of fire", 
"Water to Fire",
"Life to Fire", 
"Sure-fire", 
"Mote of Fire", 
"Fire a powerful", 
"Fire Eater",
"Breathe fire", 
"Fire Elemental", 
"Natural Fire", 
"cooking fire", 
"chaotic fire",
"shield of fire", 
"Soul Fire", 
"fire at the enemy", 
"You fire", 
"Fire a freezing",
"Fire a blast", 
"with fire",
"greater fire",
"Fire totem",
"_Fire_", --Skada compatibility
    -- Frost
"Frost Talents", 
"Frost Nova", 
"Frost Armor", 
"Frost Shock", 
"Frost Trap",
"Frost trap", 
"frost trap", 
"Frost Resistance Totem", 
"of Frost", 
"of frost",
"Frost Protection", 
"Frost Oil", 
"Frost Tiger", 
"Frost Arrow", 
"with frost",
"frost churns", 
"Frost Strike", 
"Frost Witch", 
"Frost Power", 
"Frost Lotus",
"Frost Fever", 
"Frost Ward", 
"Frost Presence", 
"Frost and Unholy", 
"Frost or Unholy",
"1 Frost",
"_Frost_", --skada compatibility
    -- Shadow
"Shadow Talents", 
"Shadow Flame", 
"Shadow Bolt", 
"Shadow Word", 
"Shadow energy",
"Shadow Trance", 
"Shadow Oil", 
"Shadow Silk", 
"Zandalarian Shadow", 
"of Shadow",
"Shadow Protection", 
"Shadow Crescent", 
"Shadow Hood", 
"Shadow Goggles",
"Flash Shadow", 
"Shadow Shot", 
"Shadow Priest", 
"Shadow Dance", 
"Primal Shadow",
"Shadow Power", 
"Shadow Armor", 
"Shadow Draenite", 
"Deep Shadow", 
"Eternal Shadow",
"eternal shadow", 
"Shadow Crystal", 
"Crystallized Shadow", 
"crystallized shadow",
"Life to Shadow", 
"element of shadow", 
"Earth to Shadow", 
"Mote of Shadow",
"Shadow Pearl", 
"Shadow Jade", 
"Shadow Embrace", 
"Shadow's Embrace", 
"Shadow Bite",
"shadow magic",
"Shadow Vault",
"_Shadow_", --Skada compatibility
    -- Holy
"Holy Talents", 
"holy spirit", 
"Holy Energy", 
"Holy energy", 
"Holy Shield",
"holy shield", 
"Holy Shock", 
"Holy Light", 
"holy light", 
"Holy Fire", 
"Holy Power",
"Holy power", 
"holy power", 
"Holy Candle", 
"Holy Mightstone", 
"Holy Protection",
"Holy Wrath", 
"Holy Nova", 
"Holy Vengeance", 
"_Holy_", --Skada/DrDamage compatiblity
"Holy and Discipline",
"Holy flames",
    -- Nature
"Nature's Guard", 
"Nature's Grace", 
"of nature", 
"of Nature", 
"Nature Protection",
"Nature Armor", 
"Unleashed Nature", 
"Nature's Swiftness", 
"Nature Resistance Totem",
"Nature's Majesty", 
"Nature's Grasp",
"_Nature_", --Skada compatibility
}
